#!/bin/sh

mute="$(pactl get-sink-mute @DEFAULT_SINK@ 2>/dev/null | awk '{print $2}')"
vol="$(pactl get-sink-volume @DEFAULT_SINK@ 2>/dev/null | awk 'NR==1{print $5}')"

[ -z "$vol" ] && exit 0

if [ "$mute" = "yes" ]; then
    printf "mute"
else
    printf "%s" "$vol"
fi
